variable "aws_instance_ami_name" {}
variable "aws_instance_type" {}
variable "aws_instance_ami_tag" {}
variable "aws_instance_volume_type" {}
variable "aws_instance_volume_size" {}
variable "aws_instance_root_block_device_iops" {}
variable "aws_instance_root_block_device_encrypted" {}
variable "aws_instance_root_block_device_kms_key_id" {}
variable "aws_instance_delete_on_termination" {}
variable "aws_instance_associate_public_ip_address" {}
variable "aws_instance_vpc_security_group_ids" {}
variable "aws_instance_user_data" {}
variable "ec2_instance_iam_instance_profile_name" {}