name: HelloWorldTestingDocument
description: This is hello world testing document.
schemaVersion: 1.0

parameters:
  - S3BucketScript:
      type: string
      default: 'ec2inspackagebucket0'
      description: The S3 bucket name where the script is stored.

phases:
  - name: 'build'
    steps:
      - name: DownloadScript
        action: S3Download
        timeoutSeconds: 60
        onFailure: Continue
        maxAttempts: 10
        inputs:
          - source: "s3://{{ S3BucketScript }}/ubuntu/ubuntu_bootstrap.sh"
            destination: '/tmp/configureEC2.sh'
      - name: VerifyFileDownload
        action: ExecuteBash
        inputs:
          commands:
            - ls -l /tmp/
            - cat /tmp/configureEC2.sh || echo "File not found or unreadable"
