name: HelloWorldTestingDocument
description: This is hello world testing document.
schemaVersion: 1.0

phases:
  - name: 'build'
    steps:
      - name: DownloadScript
        action: S3Download
        timeoutSeconds: 60
        onFailure: Continue
        maxAttempts: 10
        inputs:
          - source: 's3://ec2inspackagebucket0/ubuntu/ubuntu_bootstrap.sh'
            destination: '/tmp/configureEC2.sh'
      - name: VerifyFileDownload
        action: ExecuteBash
        inputs:
          commands:
            - ls -l /tmp/
            - cat /tmp/configureEC2.sh || echo "File not found or unreadable"
